services:
  qdrant:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  mindsdb:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  mindsdb-http-proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  ollama:
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
